Assignments/number functions
bhs-intro-to-programming/szetingchen pull request #1
Opened 2022-09-13 21:39 UTC by szetingchen

2022-09-13 23:36 UTC, gigamonkey requested changes
Please change to the syntax I showed you then I'll approve this.

2022-09-13 23:36 UTC, gigamonkey commented on assignments/number-functions/code.js
> +function add (a,b) {
These all look good except I'd like you to use the function definition syntax I teach in the Functions slides.
```suggestion
const add = (a,b) => {
```

This is legal syntax but I'm using the other one for reasons and I'd like everyone to get used to it.

2022-09-13 23:36 UTC, gigamonkey commented on assignments/number-functions/code.js
> +//That was fun, I like this kind of thing
🎉

2022-09-14 21:40 UTC, szetingchen commented on assignments/number-functions/code.js
> +//That was fun, I like this kind of thing
@gigamonkey changed the syntax

2022-09-14 23:28 UTC, gigamonkey approved these changes
Looks good. Ship it!

2022-09-14 23:28 UTC, gigamonkey commented on assignments/number-functions/code.js
> +  return Math.sqrt(((Math.abs(a-c))**2)+((Math.abs(b-d))**2))
Oh, one last comment, because you like math: Note that you don't really need `Math.abs` here since squaring a number always gives you a positive value. This is fine and correct but would be equally correct without the two calls to `Math.abs`.

2022-09-15 21:48 UTC, merged