Genetic To Be Or Not To Be
bhs-intro-to-programming/szetingchen pull request #46
Opened 2023-03-08 23:13 UTC by szetingchen

2023-03-09 23:32 UTC, gigamonkey requested changes
Reasonable start. a few things that aren't right and a few that could be done more simply. Also, can you delete the code in `script.js` that you don't need.

2023-03-09 23:32 UTC, gigamonkey commented on projects/genetic-algorithm/public/scripts/genetics.js
> +    const characters = "abcdefghijlmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789,./;-=' ";
Since this is a constant value, you should probably define it once at the top of the file.

2023-03-09 23:32 UTC, gigamonkey commented on projects/genetic-algorithm/public/scripts/genetics.js
> +const randomCharacterGenerator = () => {
This function is a) too complicated and b) I'm not sure it's uniformly random in the sense that any character is equally likely. You should be able to write a 'select one character at random from a string' function in like one line.

2023-03-09 23:32 UTC, gigamonkey commented on projects/genetic-algorithm/public/scripts/genetics.js
> +            letters.push(randomCharacterGenerator);
You need to actually _call_ `randomCharacterGenerator`

2023-03-09 23:32 UTC, gigamonkey commented on projects/genetic-algorithm/public/scripts/genetics.js
> +        cases.push(letters.reduce((str, s) => str.concat(s), ''));
That works and is a nice use of `reduce` but you can also just use `letters.join('')` to join an array of strings into a single string.

2023-03-13 21:53 UTC, szetingchen commented on projects/genetic-algorithm/public/scripts/genetics.js
> +    const characters = "abcdefghijlmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789,./;-=' ";
that makes sense

2023-03-16 03:16 UTC, gigamonkey approved these changes
this is looking very reasonable. does it work?

2023-03-16 03:16 UTC, gigamonkey commented on projects/genetic-algorithm/public/scripts/genetics.js
> +};
Glad you had fun writing quicksort. Next time you can just write:

```javascript
cases.sort((a, b) => b.fitness - a.fitness)
```

2023-03-16 03:16 UTC, gigamonkey commented on projects/genetic-algorithm/public/scripts/genetics.js
> +    return string[index];
At this point you might as well get rid of the variable and just write:

```
return string[Math.floor(Math.random() * string.length)];
```

2023-03-16 03:16 UTC, gigamonkey commented on projects/genetic-algorithm/public/scripts/genetics.js
> +        cases.push(letters.join(''));
Any time you have nested loops you should ask of the inner loop should go in its own function. Sometimes, like when you're walking through a 2d-array or something the answer may be "no", but in a case like this, I think it would be nice to break out the inner loop as a function called something like `randomString` that maybe takes the length of the string and returns a randomly generated string of that length. Then the outer loop turns into just:

```javascript
for (let i = 0; i < casesInGen; i++) {
  cases.push(randomString(stringLength));
}
```

which is very readable. Or you could go all the way to:

```javascript
const cases = Array(casesInGen).fill().map(() => randomString(stringLength));
```

2023-03-16 03:16 UTC, gigamonkey commented on projects/genetic-algorithm/public/scripts/genetics.js
> +    };
This would be a great place to use `map`.

2023-03-16 03:16 UTC, gigamonkey commented on projects/genetic-algorithm/public/scripts/genetics.js
> +};
This function is doing a lot. I'd try to break it up into some smaller functions.

2023-03-17 19:05 UTC, szetingchen commented
No, I tested it and we found that the algorithm now has to keep the first and last half intact; it can't insert characters.

2023-03-22 02:56 UTC, gigamonkey approved these changes
This looks pretty good so I left a bunch of comments about how you can write this more concisely and elegantly using HOFs.

2023-03-22 02:56 UTC, gigamonkey commented on projects/genetic-algorithm/public/scripts/genetics.js
> +let currGen = zeroGeneration(41);
Intead of 41 how about `targetString.length`; that way if you change the target string this code will still work.

2023-03-22 02:56 UTC, gigamonkey commented on projects/genetic-algorithm/public/scripts/genetics.js
> +    };
Why two loops here? Maybe better to write one loop through `parents` and in that loop push the four things onto `nextGen` directly. Or even better, write an `offspring` function so you can write this:

```javascript
const nextGen = parents.flatMap((p1, i) => offspring(p1, parents[i + 1]);
``` 

Obviously `offspring` will need to deal with the case that it's second argument is `undefined` to handle the case where `parents[i + 1]` goes off the end of the array but that's pretty easy.

2023-03-22 02:56 UTC, gigamonkey commented on projects/genetic-algorithm/public/scripts/genetics.js
> +};
You should definitely be able to write this in one line with `Array(stringLength)` and then some `fill` and `map` before finally `join`ing everything.

2023-03-22 02:56 UTC, gigamonkey commented on projects/genetic-algorithm/public/scripts/genetics.js
> +    };
You should be able to compute `zeroGen` in one step in the map at line 49 without having to create an intermediate array.

2023-03-22 18:39 UTC, gigamonkey approved these changes
A few more comments.

2023-03-22 18:39 UTC, gigamonkey commented on projects/genetic-algorithm/public/scripts/genetics.js
> +        letters.push(characters[Math.floor(Math.random() * characters.length)]);
heh, whoops. I missed that bug.

2023-03-22 18:39 UTC, gigamonkey commented on projects/genetic-algorithm/public/scripts/genetics.js
> +    return { string, fitness }
One useful trick is to arrange your fitness score so that perfect fitness (if it exists) is 1.0. In this case that is easily achieved by defining fitness as _number of matching letters_ / _length of string_. Then you can do things like run the algorithm until you achieve a fitness of 1 and it will work for any length string.

2023-03-22 18:39 UTC, gigamonkey commented on projects/genetic-algorithm/public/scripts/genetics.js
> +};
You should try changing this loop to run until fitness === 1 (assuming you take my earlier suggestion about defining fitness so 1 is perfect fitness) and experiment with different population sizes to see if it always finds a solution. With your current population size it seems like it doesn't always. You might also try just logging `currGen[0]` to see the best member of each generation rather than all of them.

2023-05-01 21:59 UTC, merged