Assignments/recursion
bhs-intro-to-programming/szetingchen pull request #48
Opened 2023-04-10 22:32 UTC by szetingchen

2023-04-11 03:11 UTC, gigamonkey requested changes
Good work so far! Keep going.

2023-04-11 03:11 UTC, gigamonkey commented on assignments/recursion/code.js
> +    return sum(arr)
You're not shrinking the problem at all so this is an infinite recursion.

2023-04-21 04:12 UTC, szetingchen commented on assignments/recursion/code.js
> +    return sum(arr)
right

2023-04-21 19:21 UTC, gigamonkey approved these changes

2023-04-21 21:22 UTC, merged