Assignments/images challenge
bhs-intro-to-programming/szetingchen pull request #5
Opened 2022-09-15 21:50 UTC by szetingchen

2022-09-16 20:22 UTC, gigamonkey reviewed
Neither approving this nor requesting changes as you obviously have more functions to write. But this looks like a good start. You might try using some `for` loops.

2022-09-16 20:22 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +const lineOfCircles = (radius) => {
You can leave function definitions uncommented. They don't do anything unless you call them. And if they're uncommented you can play with them from the REPL or just add a call to see what they do.

2022-09-16 20:22 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +const lineOfCircles = (radius) => {
Also the code shows up nicely colorized on GitHub when it's not commented out which makes it easier to read and comment on.

2022-09-21 00:13 UTC, gigamonkey commented
Hey, before you make more changes, can you make the changes I requested about uncommenting out all the function definitions. It'll make it a lot easier for me to review the code.

2022-09-21 21:36 UTC, szetingchen commented
Added the function definitions

2022-09-22 04:21 UTC, gigamonkey reviewed
As we talked about at the end of class, I think you can probably simplify your checkboard code and that'll make it easier to get working right. Keep on going though; you're on the right track.

2022-09-22 04:21 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +  let x = 0
This looks good. Though you should definitely try recasting some of these to use `for` loops instead of `while` loops.

2022-09-22 04:21 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +    color = 'blue'
This indentation is a bit off. Right click in the editor and select "Format document" from the menu that pops up.

2022-09-27 00:57 UTC, gigamonkey requested changes
Left some comments about ways you should try to simplify this code.

2022-09-27 00:57 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +    while (x < height / 2) {
`x` never changes which means this is an infinite loop which means eventually you try to draw a circle with a negative radius and get this nasty error message:

`IndexSizeError: Failed to execute 'ellipse' on 'CanvasRenderingContext2D': The major-axis radius provided (-8.52651e-14) is negative. (line 45, column 7) of http://localhost:8080/assignments/simple-draw/frame/framework.js`

2022-09-27 00:57 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +  if (height <= width) {
The only difference between the code in the two branches of this `if` statement is a few places where you use `width` in one branch and `height` in the other. Can you think of a way to have only one copy of this code and refer to the correct value of `width` or `height`, depending on which one is smaller?

2022-09-27 00:57 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +  if (height <= width) {
Same comment as about the `if` statement in `concentricCircles`.

2022-09-27 00:57 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +const notReallyCurved = (lines) => {
Is this one done? It doesn't seem to work. (I'm not sure how much it got messed up by the change in size of the drawing area but it doesn't draw nearly enough lines.)

2022-09-27 00:57 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +const notReallyCurved = (lines) => {
Nice to see you using a `for` loop though. ;-)

2022-09-30 17:11 UTC, gigamonkey approved these changes
Left some comments you should read. Up to you if you want to make any changes but you're free to merge.

2022-09-30 17:11 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +    drawLine(0, height - (position * (height / lines)), height - (position * (height / lines)), height, 0)
This code would definitely benefit from breaking out some of these common expressions into variables. It makes the individual expressions easier to read. For instance I would refactor this into:

```javascript
const notReallyCurved = (lines) => {
  const gap = height / lines;
  for (let p = 0; p != lines + 1; p++) {
    const shift = height - p * gap;
    drawLine(0, shift, shift, height, 'black')
  }
}
```

2022-09-30 17:11 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +  for(let xPos = (width - height+cExtra)/2;xPos < width - ((width - height)- cExtra)/2-radius; xPos += diameter){
If you want a challenge you could try to recast this to use a single `for` loop. But not necessary. I'm not crazy about the way you use `xCheese` (also what does that name mean?!). I'd rather you just compute what it is directly rather than relying on me to trace through the loop to understand that it's going to end up being the greatest value of `xPos`. (That's not terrible but it's a bit complicated to understand.)

2022-09-30 17:11 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +      let rand = Math.random()
Just to by annoying I'd suggest that *this* variable is *not* needed. Since it's only used in one place (on the next line) and `Math.random()` is not a complicated expression, I'd just write it directly in the `if` condition.

2022-09-30 17:11 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +    if (color === 'red') {
This is fine but if you remember the ternary operator (`?:`) from the pig latin assignment you could write this more concisely as:

```javascript
color = color === 'red' ? 'blue' : 'red';
```

2022-10-01 03:31 UTC, szetingchen commented on assignments/images-challenge/code.js
> +  for(let xPos = (width - height+cExtra)/2;xPos < width - ((width - height)- cExtra)/2-radius; xPos += diameter){
Haha, this is mostly Ion's code, not mine. We were trying to optimize this code to not use this weird 'xCheese' thing that we named it. This is a first draft of the code, so we will be improving it soon.

2022-10-07 15:51 UTC, gigamonkey requested changes
Almost there on checkerboard.

2022-10-13 03:24 UTC, gigamonkey approved these changes
Yeah, I think you should move on to arrays. You can see my solutions to these here:

https://gist.github.com/gigamonkey/e46d37848be5d5a992d4a1968b79e509

You should go ahead and merge this.

2022-10-13 21:45 UTC, merged