Assessments/unit 01
bhs-intro-to-programming/szetingchen pull request #6
Opened 2022-09-30 22:32 UTC by szetingchen

2022-10-06 16:40 UTC, gigamonkey requested changes
Left a bunch of comments.

2022-10-06 16:40 UTC, gigamonkey commented on assessments/unit-01/code.js
> +  return (totalWeight/numItems)
Correct. Note however that the `()`s on this line are redundant.

2022-10-06 16:40 UTC, gigamonkey commented on assessments/unit-01/code.js
> +  return (Math.min (widthOfArea, heightOfArea))/2
This is correct but formatted weirdly. I'd change it like this:

```suggestion
  return Math.min(widthOfArea, heightOfArea) / 2
```

2022-10-06 16:40 UTC, gigamonkey commented on assessments/unit-01/code.js
> +  return Math.floor (widthOfArea/radius)
As a matter of style, should be no space between the function name and the paren. And spaces around (most) operators

```suggestion
  return Math.floor(widthOfArea / radius)
```

2022-10-06 16:40 UTC, gigamonkey commented on assessments/unit-01/code.js
> +  return (widthOfArea-((Math.floor(widthOfArea/widthOfFigure))*widthOfFigure))/2
Not sure what's going on here. This is way too complicated. Should be:

```javascript
return (widthOfArea - widthOfFigure) / 2;
```

I think mathematically yours is almost the same because a/b * a is b but the `floor` changes it a bit.

2022-10-06 16:40 UTC, gigamonkey commented on assessments/unit-01/code.js
> +  return isASenior || invitedBySenior &&! onExclusionList
You, like many folk got tripped up by a precedence error since `&&` has higher precedence than `||` just like `*` is higher precedence than `+`. (Though it occurs to me that I may never have taught that.) So this would need `()`s to fix the order of operations:

```javascript
return (isASenior || invitedBySenior) && !onExclusionList
```

2022-10-06 16:40 UTC, gigamonkey commented on assessments/unit-01/code.js
> +  if (isCopGrouchy === true) {
You don't need to (and actually should not) compare boolean values to literal booleans. Just write 

```javascript
if (isCopGrouchy) {
```

2022-10-06 16:40 UTC, gigamonkey commented on assessments/unit-01/code.js
> +    if (mph > 65) {
Note than whenever you have code like:

```javascript
if (condition) {
  return true;
} else {
  return false;
}
```

you can (and should) simplify it to just:

```javascript
return condition;
```

I.e. the value of the condition expression is already a boolean value so just return it.

2022-10-06 16:40 UTC, gigamonkey commented on assessments/unit-01/code.js
> +}
And overall you should try to express this just as a boolean expression with no `if` statements.

2022-10-06 16:40 UTC, gigamonkey commented on assessments/unit-01/code.js
> +  if (a.length > (b.length)*2) {
Simplify to just  `return` an expression.

2022-10-06 16:40 UTC, gigamonkey commented on assessments/unit-01/code.js
> +  if (Math.abs (a-c) > Math.abs (b-c)) {
Simplify to just  `return` an expression.

2022-10-06 16:40 UTC, gigamonkey commented on assessments/unit-01/code.js
> +  return s.substring (0, Math.floor(s.length/2))
Good but formatting should be:

```suggestion
  return s.substring(0, Math.floor(s.length / 2))
```

2022-10-06 16:40 UTC, gigamonkey commented on assessments/unit-01/code.js
> +  return (s.toUpperCase() + s.toLowerCase())
Outer `()`s are redundant.

2022-10-06 16:40 UTC, gigamonkey commented on assessments/unit-01/code.js
> +  return s[s.length-1].toUpperCase()+s[s.length-1]
Need a `toLowerCase()` on the second half like you did in `upDown`

2022-10-06 16:40 UTC, gigamonkey commented on assessments/unit-01/code.js
> +  return s.search([/x/])
Search returns an index not a count. Also the regular expression syntax is wrong. Should be `/[x]/` or in this case just `/x/`. But you don't want a regex at all; you want to loop over the characters of the string and increment a variable every time you see an `'x'`.

2022-10-06 16:40 UTC, gigamonkey commented on assessments/unit-01/code.js
> +  if (s.search([/x/]) > 0) {
This would be a correct use of `search` if you had the right syntax for the regex. But the value of this function is supposed to be a boolean, i.e. `true` or `false`. Which means you could boil this one down to returning just the value of the correct expression.

2022-10-06 21:40 UTC, szetingchen commented on assessments/unit-01/code.js
> +  if (s.search([/x/]) > 0) {
ah, I must have misremembered the syntax

2022-10-06 21:40 UTC, szetingchen commented on assessments/unit-01/code.js
> +  return s[s.length-1].toUpperCase()+s[s.length-1]
got it

2022-10-06 21:41 UTC, szetingchen commented on assessments/unit-01/code.js
> +  return s.search([/x/])
right. I simply didn't have time to write the loop.

2022-10-06 21:41 UTC, szetingchen commented on assessments/unit-01/code.js
> +  return isASenior || invitedBySenior &&! onExclusionList
ohhhh, but I tried all the combinations and I think it still holds up.

2022-10-06 21:42 UTC, szetingchen commented on assessments/unit-01/code.js
> +  return (widthOfArea-((Math.floor(widthOfArea/widthOfFigure))*widthOfFigure))/2
I left the Math.floor in there because we wanted a whole number to offset by. It doesn't really make sense to offset by some decimal value.

2022-11-30 23:09 UTC, szetingchen commented
I think I fixed everything, and solved the last 3 problems

2022-12-01 01:25 UTC, gigamonkey approved these changes
Looks  good. Left a few more comments but you can go ahead and merge this.

2022-12-01 01:25 UTC, gigamonkey commented on assessments/unit-01/code.js
> +  if (num / 2 > Math.floor(num / 2)) {
This works but more idiomatic is `num % 2 === 0`. Or I guess in this case since you're checking for odd, `num % 2 !== 0` or `num % 2 === 1`. Though I'd probably just flip the clauses and also use the `?:` operator:

```javascript
  return num % 2 === 0 ? 'yes' : 'no';
```

2022-12-01 01:25 UTC, gigamonkey commented on assessments/unit-01/code.js
> +  return s[s.length - 1].toUpperCase() + s[s.length - 1].toLowerCase
Missing `()`s on the call to `toLowerCase`

And more sophisticatedly, you could just `upDown` since you already wrote it:

```javascript
return upDown(s[s.length - 1]);
```

2023-01-03 22:59 UTC, merged