Assignments/tic tac toe
bhs-intro-to-programming/szetingchen pull request #9
Opened 2022-10-27 21:37 UTC by szetingchen

2022-10-28 04:32 UTC, gigamonkey requested changes
This is obviously not done so I just left some comments for you to consider. Keep going.

2022-10-28 04:32 UTC, gigamonkey commented on assignments/tic-tac-toe/code.js
> +  [[''], [''], ['']],
I'm a bit confused about the third level of array here. Seems excessive. (I'd expect the outer array to be an array of three items, each representing a row, and each of those items to be an array of three  values, maybe three strings. You instead have the rows as arrays of three arrays of one item each.)

2022-10-28 04:32 UTC, gigamonkey commented on assignments/tic-tac-toe/code.js
> +    if (coordArray[yPos][xPos] == '') {
Unless I'm missing something, this isn't going to work with your triply-nested array discussed above: the value of `coordArray[yPos][xPos]` is going to be something like `['']` not `''`.

2022-11-03 16:36 UTC, gigamonkey requested changes
Left a bunch of suggestions of changes you should try making and then request a new review.

2022-11-03 16:36 UTC, gigamonkey commented on assignments/tic-tac-toe/code.js
> +  if ((coordArray[0][0] == player && coordArray[1][1] == player && coordArray[2][2] == player) ||
This is kind of crying out for some loops.

2022-11-03 16:36 UTC, gigamonkey commented on assignments/tic-tac-toe/code.js
> +    y < 1 / 3 * height ? yPos = 0 : y < 2 / 3 * height ? yPos = 1 : yPos = 2;
Oh. You shouldn't use `?:` for side effects such as assigning to a variable. Use it when you want an expression that computes a value. For this use a normal `if`. Or I suppose in this case you could write it like:

```javascript
yPos = y < 1 / 3 * height ? 0 : y < 2 / 3 * height ? 1 : 2;
```

I.e. use the `?:` as an expression which produces a value that you assign to a variable. But nested `?:` is probably not a great idea—too hard to read. Especially in this case when you could just use math:

```javascript
yPos = Math.floor(y / (height / 3));
```

2022-11-09 02:10 UTC, gigamonkey approved these changes
Getting there. As I said in one of my comments, I'm pretty sure this code must crash but you're on a reasonable track. Keep at it. Can you do me a favor though and merge this and open a new PR if you keep working on it? This one has quite a lot of changes in it already.

2022-11-09 02:10 UTC, gigamonkey commented on assignments/tic-tac-toe/code.js
> +      return ({ player: player, winType: 'h', winLoca: p })
The `()`s around the object are not needed here. That's only needed when you are returning an object from a function written in the shorthand style.

2022-11-09 02:10 UTC, gigamonkey commented on assignments/tic-tac-toe/code.js
> +  if (win.winType == 'h') {
I think this is going to explode if `isWinner` returns `undefined` which it will if there's no winner. (Haven't actually run your code so maybe I'm missing something but I think so.)

2022-11-09 02:10 UTC, gigamonkey commented on assignments/tic-tac-toe/code.js
> +      player == player1 ? player = player2 : player = player1
Again, don't use `=` inside the clauses of an `?:` expression. Instead write this as:

```suggestion
      player = player === player1 ? player2 : player1
```

2022-11-09 22:47 UTC, merged

2022-11-09 22:47 UTC, szetingchen commented
Merged. Will open a new PR.